services:
  pg_master:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: primary_db
    ports:
      - "5442:5432"
    volumes:
      - ./pg_master_data:/var/lib/postgresql/data
      - ./CREATE_DATABASE_TestDB:/docker-entrypoint-initdb.d/CREATE_DATABASE_TestDB.sql
      - ./Include_Table_Orders:/docker-entrypoint-initdb.d/Include_Table_Orders.sql

    restart: always
    command: [
      "postgres",
      "-c", "wal_level=logical",
      "-c", "max_replication_slots=10",
      "-c", "max_wal_senders=10"
    ]

  pg_replica:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: kamalapur_station_db
    ports:
      - "5443:5432"
    volumes:
      - ./pg_replica_data:/var/lib/postgresql/data
    restart: always

-- Connect to the primary database
\c pg_master

-- Create a publication for the Orders table.
CREATE PUBLICATION Orders_pub
   FOR TABLE Orders WITH (publish = 'insert, update, delete');

-- Connect to the replica database
\c pg_replica

-- Create a subscription to the primary database
CREATE SUBSCRIPTION Orders_sub
   CONNECTION 'host=<primary_ip> port=5432 dbname=pg_master user=replicator_user password=<secure_password> sslmode=require'
   PUBLICATION Orders_pub
   WITH (
      copy_data = true,
      create_slot = true,  
      enabled = true       
    );
